<!DOCTYPE html>
<html>

<head>
  <title>Tales from the Front End</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
  <div class="container">
    <div class="blog-header">
      <h1 class="blog-title">{{config.title}}</h1>
      <p class="lead blog-description">{{config.subtitle}}</p>
    </div>
    <div>
      {{body}}
      
    </div>
  </div>

</body>

</html>
